### ISSUE TITLE
SQL panel points a query in an included template to the same line of its parent template

### ISSUE THREAD

**Issue by lingxiaoyang** [jazzband/django-debug-toolbar#902]
Tested with:

views.py
````python
from test_debug_toolbar.models import Question

def index(request):
    return render(request, 'index.html', {'questions': Question.objects.all()})
````

index.html
````html
{% extends 'base.html' %}

{% block content %}

<h5>Hello there! This is a test for debug toolbar.</h5>

<p>Below is an included template that makes a SQL query. But in debug toolbar, it is signified in "index.html", while it should be in "inner.html".</p>

{% include 'inner.html' %}

{% endblock content %}
````

inner.html
````html
<p>Here's inner.html:</p>


<p>All questions:</p>
{{ questions }}
````

The SQL query of `Question.objects.all()` is executed at the line 5 of `inner.html`, but in the SQL panel, it is incorrectly pointed to the line 5 of its parent template `index.html`:

![image](https://cloud.githubusercontent.com/assets/8630726/21615030/c9caed1a-d1a9-11e6-8626-0b5f18f8e340.png)

Tested with current master and develop branch, and Django 1.10.4.

For the complete test Django project: https://github.com/lingxiaoyang/test_debug_toolbar

**Comment by lingxiaoyang** [comment]
I investigated a little of this issue. The problem seems to exist only on Django 1.9 and later, most probably because of the following code (reference to [utils.py](https://github.com/jazzband/django-debug-toolbar/blob/master/debug_toolbar/utils.py#L117-L142)):

````python
def get_template_context(node, context, context_lines=3):
    source = getattr(node, 'source', None)
    # In Django 1.9 template Node does not have source property, Origin does
    # not reload method, so we extract contextual information from exception
    # info.
    if source:
        line, source_lines, name = get_template_source_from_source(source)
    else:
        line, source_lines, name = get_template_source_from_exception_info(
            node, context)
````

It is very possible that function `get_template_source_from_exception_info` doesn't work accurately on `include` template tag. 

Then I tested the same code with Django 1.8, and the template tracking is working correctly:
![image](https://cloud.githubusercontent.com/assets/8630726/24054698/77662ece-0b13-11e7-974e-85688cf50252.png)

**Comment by lingxiaoyang** [comment]
Further investigation shows that Django 1.10.6 itself has the same problem when dealing with template exception, which is fixed in 1.11b1. However, Django debug toolbar gives wrong result for both versions. On an older version 1.8.11, both Django and Django debug toolbar work as expected.

Here's the comparison table:

<table>
<thead>
<th>Django version</th><th>Django</th><th>Django debug toolbar</th>
</thead>
<tbody>
<th>1.8.11</th><td><b>Correct</b><img src="https://cloud.githubusercontent.com/assets/8630726/24060362/4fb6cfee-0b29-11e7-88c3-1bd45c68d9db.png"></td><td><b>Correct</b><img src="https://cloud.githubusercontent.com/assets/8630726/24060396/76871a48-0b29-11e7-9545-eb3ea764e199.png"></td>
</tr>
<tr>
<th>1.10.6</th><td><b>Incorrect</b><img src="https://cloud.githubusercontent.com/assets/8630726/24060337/35b74cf4-0b29-11e7-8e41-090d9b610920.png"></td><td><b style="color:red">Incorrect</b><img src="https://cloud.githubusercontent.com/assets/8630726/24060419/8c21f7c4-0b29-11e7-8c19-3e943622a379.png"></td>
</tr>
<tr>
<th>1.11b1</th><td><b>Correct</b><img src="https://cloud.githubusercontent.com/assets/8630726/24060308/1526728a-0b29-11e7-8a6a-f97770290144.png"></td><td><b>Incorrect</b><img src="https://cloud.githubusercontent.com/assets/8630726/24060444/a3626752-0b29-11e7-83d8-c738eb09ff17.png"></td>
</tr>
</table>

I'll see what Django has changed in its code and perhaps submit a PR on this later.

**Comment by lingxiaoyang** [comment]
Questions to the package maintainers:

At the Django side, the bug concerning `{% include %}` and `{% extend %}` indeed exists in versions 1.9 and 1.10, and is being fixed in 1.11 LTS. However, this bugfix will not be backported to 1.9 and 1.10 (most probably because they will be out of support soon, according to Django roadmap). References: tickets [27584](https://code.djangoproject.com/ticket/27584) and [27956](https://code.djangoproject.com/ticket/27956).

At present, django-debug-toolbar copies the same code in Django to extract the template source. This code will need a small fix in order to work correctly in Django 1.11, but a more significant change will be required if we want it working with 1.9 and 1.10. You may compare the code of the [bugfix](https://github.com/django/django/pull/7686/files#diff-8cbe1fb6d589cb6e35b956704d7a1285R960) and [debug_toolbar/utils.py](https://github.com/jazzband/django-debug-toolbar/blob/master/debug_toolbar/utils.py).

The question is therefore: do we want this fix to only work with Django 1.11 LTS and keep how it is now with versions 1.9 and 1.10; or do we also provide another solution for these two older versions?

A 2nd question: do we need a unit test on this, or is it fine to just keep it the same with Django's code?

**Comment by matthiask** [comment]
I think doing the same thing the Django maintainers do is fine; I'm alright with only being correct on 1.11 upwards.

That being said, if someone wants to do the work of supporting 1.9 and 1.10 as well despite Django itself being incorrect there I certainly won't stop them. 

Unit tests are always good, and if it's possible to easily construct an unit test then it should be done (tm). If it's hard or nobody wants to invest the time then following Django is fine. If we do more than Django does by fixing the reports on 1.9 and 1.10 an unit test would clearly be a requirement though, because I expect the code involved would be more complex and we would certainly want to avoid inadvertent breakage.

**Comment by allan-simon** [comment]
i'm still seeing the issue with django-debug-toolbar 1.11 and django 1.11.23
